version: '3.8'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=movies
      - MYSQL_HOST=mysql
    ports:
      - "9906:3306"
    expose:
      - 9906
    networks:
      - shared-network
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  movie-server:
    container_name: movie-server
    restart: unless-stopped
    image: movie-server:1.0.0.
    build:
      context: movie-server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    healthcheck:
      test: curl --fail 127.0.0.1:3306 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - shared-network
    depends_on:
      - mysql
    command: sh -c "/wait && npm run dev"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  movie-client:
    container_name: movie-client
    restart: unless-stopped
    image: movie-client:1.0.0.
    build:
      context: movie-client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - movie-server

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - shared-network

networks:
  shared-network:
